# Generated by Django 5.2.5 on 2025-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
